platform :ios, '11.0'

target 'YTKNetworkDemo' do
    pod 'YTKNetwork', :path => '../'
    pod 'AFNetworking', '~> 3.2.1'
end

target 'YTKNetworkDemoTests' do
    pod 'YTKNetwork', :path => '../'
end

